# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-social-cards-1',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-social-cards-1',
                'lib_path': 'test_social_cards_1'},
  'syms': {'test_social_cards_1.core': {'test_social_cards_1.core.foo': ('core.html#foo', 'test_social_cards_1/core.py')}}}
